name: Deploy to Cloudflare

on:
  push:
    branches:
    - master
    - develop
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v23
    - uses: cachix/cachix-action@v12
      with:
        name: devenv
    - name: devenv.sh
      run: nix profile install tarball+https://install.devenv.sh/latest
    - name: build and deploy
      env:
        CLOUDFLARE_ACCOUNT_ID: ${{secrets.CLOUDFLARE_ACCOUNT_ID}}
        CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_API_TOKEN}}
        CLOUDFLARE_PROJECT: ${{vars.CLOUDFLARE_PROJECT}}
      run: devenv shell deploy
